version: '3.8'

services:
  my-db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=django-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d django-postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - account_network

  my-django:
    build: .
    container_name: django
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment: # 컨테이너 환경변수 설정
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    depends_on:
      my-db:
        condition: service_healthy
    networks:
      - account_network


volumes:
  postgres_data:

networks:
  account_network:


