[tool.black]
line-length = 88
target-version = ['py313']  # Python 버전 맞추기
skip-string-normalization = true
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
known_first_party = ["accountbook"]
skip_gitignore = true
