# Generated by Django 5.2.2 on 2025-06-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(
                error_messages={'unique': '이미 존재하는 계좌번호입니다.'},
                max_length=30,
                unique=True,
                verbose_name='계좌번호',
            ),
        ),
    ]
