# .github/workflows/checks.yml

name: Code Quality Checks

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      my-db:
        image: postgres:14

        env:
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PG_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --memory=512m

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create secret.json
        run: |
          mkdir -p config
          echo '${{ secrets.SECRET_JSON }}' > config/secret.json    

      - name: Build and start containers
        run: |
          docker compose up -d --build

      - name: Wait for Database
        run: docker compose run my-django python manage.py wait_for_db

      - name: Check code formatting with isort
        run: docker compose exec my-django isort . --check --diff

      - name: Check code formatting with black
        run: docker compose exec my-django black . --check

      - name: Apply migrations
        run: docker compose exec my-django python manage.py migrate

      - name: Run tests
        run: docker compose exec my-django python manage.py test

      - name: Cleanup containers
        run: docker compose down --volumes --remove-orphans
