# .github/workflows/checks.yml

name: Code Quality Checks

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    # Postgres & Redis 서비스만 띄워 둡니다
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PG_NAME }}
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U ${{ secrets.PG_USER }}; do
            sleep 1
          done

      - name: Run isort (import sorting)
        run: isort . --check --diff

      - name: Run black (code formatting)
        run: black . --check

      - name: Django migrations & tests
        env:
          # Django settings.py에서 os.getenv로 읽습니다
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DJANGO_ENV: development
          DB_NAME: ${{ secrets.PG_NAME }}
          DB_USER: ${{ secrets.PG_USER }}
          DB_PASSWORD: ${{ secrets.PG_PASSWORD }}
          DB_HOST: localhost
          DB_PORT: 5432
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          python manage.py wait_for_db
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput
          python manage.py test

