# .github/workflows/checks.yml

name: Code Quality Checks

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      my-db:
        image: postgres:14

        env:
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PG_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --memory=512m

      my-redis:
        image: redis:7

        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> .env
          echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> .env
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> .env
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
          echo "EMAIL_USE_TLS=${{ secrets.EMAIL_USE_TLS }}" >> .env
          echo "EMAIL_USE_SSL=${{ secrets.EMAIL_USE_SSL }}" >> .env

      - name: Build and start containers
        run: |
          docker compose up -d --build
          
      - name: Wait for my-django to be up (초기 기동 상태 확인)
        run: |
          sleep 10
          docker compose ps
          docker compose logs my-django

      - name: Wait for Database

        run: |
          sleep 30
          docker compose exec -T my-django python manage.py wait_for_db

      - name: Check code formatting with isort
        run: docker compose exec my-django isort . --check --diff

      - name: Check code formatting with black
        run: docker compose exec my-django black . --check

      - name: Apply migrations
        run: docker compose exec my-django python manage.py migrate

      - name: Run tests
        run: docker compose exec my-django python manage.py test

      - name: Cleanup containers
        run: docker compose down --volumes --remove-orphans

      - name: Show my-django logs on failure
        if: failure()
        run: docker compose logs my-django
