# .github/workflows/checks.yml

name: Code Quality Checks

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_ENV: development
      DB_NAME: ${{ secrets.PG_NAME }}
      DB_USER: ${{ secrets.PG_USER }}
      DB_PASSWORD: ${{ secrets.PG_PASSWORD }}
      DB_HOST: localhost
      DB_PORT: 5432
      REDIS_HOST: localhost
      REDIS_PORT: 6379

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PG_NAME }}
        ports:
          - 5432:5432

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort

      - name: Create .env
        run: |
          cat <<EOF > .env
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DJANGO_ENV=development
          DB_NAME=${{ secrets.PG_NAME }}
          DB_USER=${{ secrets.PG_USER }}
          DB_PASSWORD=${{ secrets.PG_PASSWORD }}
          DB_HOST=localhost
          DB_PORT=5432
          REDIS_HOST=localhost
          REDIS_PORT=6379
          EOF

      - name: Run isort (import sorting)
        run: isort . --check --diff

      - name: Run black (code formatting)
        run: black . --check

      - name: Wait for database
        run: python manage.py wait_for_db

      - name: Apply migrations
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      - name: Run tests
        run: python manage.py test

      - name: Cleanup services
        if: always()
        run: docker compose down --volumes --remove-orphans
