# .github/workflows/checks.yml

name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      my-db:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PG_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Docker containers
        run: docker compose up -d --build

      - name: Wait for database to be ready
        run: sleep 15

      - name: Apply migrations
        run: docker compose exec my-django python manage.py migrate

      - name: Run tests
        run: docker compose exec my-django python manage.py test

      - name: Cleanup containers
        run: docker compose down --volumes --remove-orphans



